name: Pre-Commit Workflow

on:
  workflow_call:

jobs:
  precommit:
    runs-on: ubuntu-latest
    name: Pre-Commit Checks
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install pre-commit
        run: |
          python -m pip install --upgrade pip
          pip install pre-commit
      - name: Run pre-commit hooks
        run: pre-commit run --all-files --show-diff-on-failure --color=always

      # - name: Validate PR title (commitlint)
      #   if: github.event_name == 'pull_request'
      #   run: |
      #     npm install --save-dev @commitlint/cli @commitlint/config-conventional
      #     echo 'module.exports = {
      #       extends: ["@commitlint/config-conventional"],
      #       rules: {
      #         "type-enum": [2, "always", ["feat","fix","docs","style","refactor","perf","test","chore","ci","build","revert"]],
      #         "type-case": [2, "always", "lower-case"],
      #         "type-empty": [2, "never"],
      #         "subject-empty": [2, "never"],
      #         "subject-case": [2, "never", ["upper-case"]],
      #         "subject-full-stop": [2, "never", "."],
      #         "header-max-length": [2, "always", 72]
      #       }
      #     }' > commitlint.config.js
      #     echo "${{ github.event.pull_request.title }}" | npx commitlint --config commitlint.config.js
